// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package shop

import (
	"database/sql"
)

type AdminUser struct {
	Email string
}

type Coupon struct {
	CouponID            int64
	CouponCode          string
	MinPurchaseQuantity sql.NullInt64
	DiscountPercentage  int64
	Enabled             bool
	Public              bool
	RedemptionLimit     sql.NullInt64
}

type Order struct {
	OrderID          int64
	Name             string
	MatricNumber     string
	PaymentReference sql.NullString
	Status           string
	CouponCode       sql.NullString
}

type OrderItem struct {
	OrderID   int64
	ProductID string
	UnitPrice int64
	Amount    int64
	Variant   string
}

type Product struct {
	ProductID        int64
	Name             string
	BasePrice        int64
	DefaultImageUrl  string
	Variants         string
	VariantImageUrls string
	Enabled          bool
}
