// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package shop

import (
	"database/sql"
	"time"
)

type AdminUser struct {
	Email string
}

type Coupon struct {
	CouponID            int64
	CouponCode          string
	StripeID            string
	MinPurchaseQuantity sql.NullInt64
	DiscountPercentage  int64
	Enabled             bool
	Public              bool
	RedemptionLimit     sql.NullInt64
}

type Order struct {
	ID               int64
	OrderID          string
	Name             string
	MatricNumber     string
	Email            string
	PaymentReference sql.NullString
	PaymentTime      sql.NullTime
	CollectionTime   sql.NullTime
	Cancelled        bool
	CouponID         sql.NullInt64
}

type OrderItem struct {
	OrderID     string
	ProductID   string
	ProductName string
	UnitPrice   int64
	Amount      int64
	ImageUrl    string
	Variant     string
}

type Product struct {
	ProductID        int64
	Name             string
	BasePrice        int64
	DefaultImageUrl  string
	Variants         string
	VariantImageUrls string
	Enabled          bool
}

type StoreClosure struct {
	ID              int64
	StartTime       time.Time
	EndTime         time.Time
	UserMessage     string
	AllowOrderCheck bool
	Deleted         bool
}
