// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package shop

import (
	"context"
	"database/sql"
)

const authAdminUser = `-- name: AuthAdminUser :one
SELECT
	email
FROM
	admin_users
WHERE
	email = ?
`

func (q *Queries) AuthAdminUser(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, authAdminUser, email)
	err := row.Scan(&email)
	return email, err
}

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT
	COUNT(*)
FROM
	admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :exec
INSERT INTO admin_users (
	email
) VALUES (
	?
) ON CONFLICT DO NOTHING
`

func (q *Queries) CreateAdminUser(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, createAdminUser, email)
	return err
}

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
	coupon_code, min_purchase_quantity, discount_percentage, enabled
) VALUES (
	?, ?, ?, ?
) RETURNING coupon_id
`

type CreateCouponParams struct {
	CouponCode          string
	MinPurchaseQuantity sql.NullInt64
	DiscountPercentage  int64
	Enabled             bool
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCoupon,
		arg.CouponCode,
		arg.MinPurchaseQuantity,
		arg.DiscountPercentage,
		arg.Enabled,
	)
	var coupon_id int64
	err := row.Scan(&coupon_id)
	return coupon_id, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
	name, matric_number, payment_reference, status, coupon_code
) VALUES (
	?, ?, ?, 'PLACED', ?
) RETURNING order_id
`

type CreateOrderParams struct {
	Name             string
	MatricNumber     string
	PaymentReference sql.NullString
	CouponCode       sql.NullString
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.Name,
		arg.MatricNumber,
		arg.PaymentReference,
		arg.CouponCode,
	)
	var order_id int64
	err := row.Scan(&order_id)
	return order_id, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (
	order_id, product_id, unit_price, amount, variant
) VALUES (
	?, ?, ?, ?, ?
)
`

type CreateOrderItemParams struct {
	OrderID   int64
	ProductID string
	UnitPrice int64
	Amount    int64
	Variant   string
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.UnitPrice,
		arg.Amount,
		arg.Variant,
	)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
	name, base_price, default_image_url, variants, variant_image_urls, enabled
) VALUES (
	?, ?, ?, ?, ?, ?
) RETURNING product_id
`

type CreateProductParams struct {
	Name             string
	BasePrice        int64
	DefaultImageUrl  string
	Variants         string
	VariantImageUrls string
	Enabled          bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.BasePrice,
		arg.DefaultImageUrl,
		arg.Variants,
		arg.VariantImageUrls,
		arg.Enabled,
	)
	var product_id int64
	err := row.Scan(&product_id)
	return product_id, err
}

const deleteAdminUser = `-- name: DeleteAdminUser :exec
DELETE FROM
	admin_users
WHERE
	email = ?
`

func (q *Queries) DeleteAdminUser(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteAdminUser, email)
	return err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT
	email
FROM
	admin_users
`

func (q *Queries) ListAdminUsers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT
	order_id, product_id, unit_price, amount, variant
FROM
	order_items
WHERE
	order_id = ?
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.ProductID,
			&i.UnitPrice,
			&i.Amount,
			&i.Variant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
	product_id, name, base_price, default_image_url, variants, variant_image_urls, enabled
FROM
	products
WHERE
	enabled = TRUE
	OR CAST(?1 AS BOOLEAN)
`

func (q *Queries) ListProducts(ctx context.Context, includeDisabled bool) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, includeDisabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.BasePrice,
			&i.DefaultImageUrl,
			&i.Variants,
			&i.VariantImageUrls,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCoupons = `-- name: ListPublicCoupons :many
SELECT
	coupon_id, coupon_code, min_purchase_quantity, discount_percentage, enabled, public, redemption_limit
FROM
	coupons
WHERE
	enabled = TRUE
	AND public = TRUE
`

func (q *Queries) ListPublicCoupons(ctx context.Context) ([]Coupon, error) {
	rows, err := q.db.QueryContext(ctx, listPublicCoupons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.CouponID,
			&i.CouponCode,
			&i.MinPurchaseQuantity,
			&i.DiscountPercentage,
			&i.Enabled,
			&i.Public,
			&i.RedemptionLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupOrder = `-- name: LookupOrder :many
SELECT
	order_id, name, matric_number, payment_reference, status, coupon_code
FROM
	orders
WHERE
	CAST(order_id AS TEXT) = ?
	OR matric_number = ? COLLATE NOCASE
	OR payment_reference = ? COLLATE NOCASE
`

type LookupOrderParams struct {
	OrderID          int64
	MatricNumber     string
	PaymentReference sql.NullString
}

func (q *Queries) LookupOrder(ctx context.Context, arg LookupOrderParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, lookupOrder, arg.OrderID, arg.MatricNumber, arg.PaymentReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.Name,
			&i.MatricNumber,
			&i.PaymentReference,
			&i.Status,
			&i.CouponCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCouponEnabled = `-- name: SetCouponEnabled :exec
UPDATE
	coupons
SET
	enabled = ?
WHERE
	coupon_id = ?
`

type SetCouponEnabledParams struct {
	Enabled  bool
	CouponID int64
}

func (q *Queries) SetCouponEnabled(ctx context.Context, arg SetCouponEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setCouponEnabled, arg.Enabled, arg.CouponID)
	return err
}

const setProductEnabled = `-- name: SetProductEnabled :exec
UPDATE
	products
SET
	enabled = ?
WHERE
	product_id = ?
`

type SetProductEnabledParams struct {
	Enabled   bool
	ProductID int64
}

func (q *Queries) SetProductEnabled(ctx context.Context, arg SetProductEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setProductEnabled, arg.Enabled, arg.ProductID)
	return err
}

const updateCoupon = `-- name: UpdateCoupon :exec
UPDATE
	coupons
SET
	coupon_code = ?,
	min_purchase_quantity = ?,
	discount_percentage = ?,
	enabled = ?,
	public = ?
WHERE
	coupon_id = ?
`

type UpdateCouponParams struct {
	CouponCode          string
	MinPurchaseQuantity sql.NullInt64
	DiscountPercentage  int64
	Enabled             bool
	Public              bool
	CouponID            int64
}

func (q *Queries) UpdateCoupon(ctx context.Context, arg UpdateCouponParams) error {
	_, err := q.db.ExecContext(ctx, updateCoupon,
		arg.CouponCode,
		arg.MinPurchaseQuantity,
		arg.DiscountPercentage,
		arg.Enabled,
		arg.Public,
		arg.CouponID,
	)
	return err
}

const updateOrderStatusID = `-- name: UpdateOrderStatusID :exec
UPDATE
	orders
SET
	status = ?
WHERE
	order_id = ?
`

type UpdateOrderStatusIDParams struct {
	Status  string
	OrderID int64
}

func (q *Queries) UpdateOrderStatusID(ctx context.Context, arg UpdateOrderStatusIDParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatusID, arg.Status, arg.OrderID)
	return err
}

const updateOrderStatusPaymentRef = `-- name: UpdateOrderStatusPaymentRef :exec
UPDATE
	orders
SET
	status = ?
WHERE
	payment_reference = ?
`

type UpdateOrderStatusPaymentRefParams struct {
	Status           string
	PaymentReference sql.NullString
}

func (q *Queries) UpdateOrderStatusPaymentRef(ctx context.Context, arg UpdateOrderStatusPaymentRefParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatusPaymentRef, arg.Status, arg.PaymentReference)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE
	products
SET
	name = ?,
	base_price = ?,
	default_image_url = ?,
	variants = ?,
	variant_image_urls = ?,
	enabled = ?
WHERE
	product_id = ?
`

type UpdateProductParams struct {
	Name             string
	BasePrice        int64
	DefaultImageUrl  string
	Variants         string
	VariantImageUrls string
	Enabled          bool
	ProductID        int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.BasePrice,
		arg.DefaultImageUrl,
		arg.Variants,
		arg.VariantImageUrls,
		arg.Enabled,
		arg.ProductID,
	)
	return err
}

const useCoupon = `-- name: UseCoupon :one
SELECT
	coupon_id, coupon_code, min_purchase_quantity, discount_percentage, enabled, public, redemption_limit
FROM
	coupons
WHERE
	coupon_code = ?
	AND enabled = TRUE
`

func (q *Queries) UseCoupon(ctx context.Context, couponCode string) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, useCoupon, couponCode)
	var i Coupon
	err := row.Scan(
		&i.CouponID,
		&i.CouponCode,
		&i.MinPurchaseQuantity,
		&i.DiscountPercentage,
		&i.Enabled,
		&i.Public,
		&i.RedemptionLimit,
	)
	return i, err
}
